### ISSUE TITLE
학습된 모델 요청

### ISSUE THREAD

**Issue by janguck** [rungjoo/Stable-Style-Transformer#2]
안녕하세요. 좋은 연구 공개해주셔서 감사합니다. 

학습하려고 했는데, 80시간이 넘는 시간이 걸리는 것 같습니다. 

혹시 학습된 모델 가중치를 공유해주실 수 있을까요?

감사합니다.

**Comment by rungjoo** [comment]
안녕하세요. 제가 실험을 현재 쓰고있는 서버가 아닌 이전 서버로 해서 모델 권한이 저한테도 아쉽게도 없네요.. 있다고 해도 회사 소속이기 때문에 자유롭게 외부에 배포하는게 가능한지는 또 모르겠어요.

저는 V100 16GB에서 실험을 했었는데 2일 정도 걸렸었어요 (생성모델만). GPU가 넉넉치 않아 저도 학습도 오래걸렸고 모델 사이즈를 키우면 OOM이 나왔었던 기억이 나네요. 그 외에 delete나 평가할 때 쓰는 GPT LM 모델은 그리 오래 안걸렸던 것으로 기억해요. 

도움을 못드려서 죄송합니다.

**Comment by janguck** [comment]
답변 감사합니다. 

시간 Cost를 이유로 데이터셋을 10,000개 정도로 축소하고 학습하였는데 One Token Prediction의 문제가 있네요,, 

Train - Step 1, 2의  학습코드를 실행하고 생성되는 결과물을 확인했는데, 더 확인 해야될 내용이 있을까요?

**Comment by rungjoo** [comment]
네 안녕하세요.

혹시 어떤 문젠가 발생하셨는지 설명좀 해주실 수 있나요?
- one token prediction이라 함은!?

생성되는 결과물이 제대로 안나오는 상태인가요?

**Comment by janguck** [comment]
넵 맞습니다. 
evaluation/my_model/SST 에 있는 모델의 Inference 결과인데, 

ever since joes has changed hands it 's just gotten worse and worse .	however since joes has hands it 's just gotten great and delicious .	0

이게 was was was 형태로 one token prediction이 되고 있습니다. 

감사합니다.

**Comment by rungjoo** [comment]
연말이라 답장이 늦어졌네요;; 질문자님은 연말에도 열심히 연구하시는군요ㅎㅎ..

말씀하신 문제는 아시다시피 사실 모델링에서 고려하지는 못했죠. 출력에서 나왔던 단어에 대한 패널티를 주지도 않았고요.

제가 논문에서 실험측정한 결과는 evaluation/{dataset}에 있는데요.
여기서 모델이 출력했던 결과를 한 번 간단히 봤는데요.
그 중 evaluation/amazon/my_model_paper/sentiment.test.0.SST_50_06에서 163번째 결과가 다음과 같이 있네요.
there are that make it room with the phone the the the the the the the the the the the
즉, the가 끝에 계속 생성되는 문제가 있죠.

사실 이 부분도 질문자님이 말씀하신 것과 비슷할 수 있어요. the로 계속 발생하는거니까요.
즉, 데이터를 full로 써도 발생하는 문제인 것 같네요.

이 문제는 논문 모델에서 발생하는 게 맞는 것 같고, 이 부분을 컨트롤할만한 스킬을 모델링할 때 추가하면 더 발전되지 않을까 싶네요.. 
저는 시도 안해봤지만, 자연어 생성에서 이러한 문제를 생성될 token 확률에서 이전에 생성되었던 token이라면 패널티를 줘서 확률을 낮춰 반복되는 token를 생성하지 않도록 하게끔 하는 것으로 알고 있거든요. (정확히 명칭이 기억이 안나네요)
- 검색해보니 다음과 같은 참고 논문이 있네요. [Neural Text Generation With Unlikelihood Training ](https://arxiv.org/pdf/1908.04319.pdf)

아니면, top-1으로 토큰을 생성하지 말고 1) beam-search라든가, 혹은 2) LM 토큰 확률 + something을 이용하여 토큰을 선택하는 식, 3) 길이가 길어지는 것을 패널티 주는 식 등등으로 발전시킬 수 있지 않을까 싶네요

**Comment by janguck** [comment]
안녕하세요. 답변 감사드립니다. 

말씀해주신 내용이 결과의 한계로 이어질 수 있다고 생각합니다.
제가 문의드린 내용은  재학습 하였을 때 "evaluation/amazon/my_model_paper/sentiment.test.0.SST_50_06" 처럼 결과가 안나온다는 점입니다. 모든 결과가 one token prediction을 하고 있습니다. 

제가 사용한 데이터셋은 yelp이고, README.md 에 적어 주신 것처럼  "Step 1: Train classifier", "Step 2: Train generator"로 학습한 후 "generation_model/inference.ipynb"을 사용해서 결과물을 뽑아냈습니다. (gen_model은 주석으로 이루어져있어 임의로 풀었음) 

이와 같이 했을 때 제안해주신 모델의 예시처럼 결과가 안나오는 상황입니다.(one token prediction) 

혹시 제가 튜토리얼을 잘못 이해하였거나 사용하고 있는지 알고 싶습니다. 

감사합니다. 

추가로 데이터셋은 제안해주신것처럼 https://github.com/lijuncen/Sentiment-and-Style-Transfer 에서 다운받아서 사용했습니다.

**Comment by rungjoo** [comment]
아 질문을 잘못 이해했었네요. 말씀하신대로 하면 됩니다. 

(inference.ipynb에서 학습된 모델을 제대로 로드하신것은 맞으시죠?)
inference.ipynb은 제가 깔끔하게 정리해서 올린거라기보단, 참고용으로 올린 코드인데 In [5] 부분이 실행되면 테스트 데이터에 대해 style transfer을 하게 된 text을 저장하게 될 것입니다.

이렇게 해서 뽑은 데이터가 one token prediction 문제가 발생한거라는 거죠?
저는 학습할 때, 딱히 이런 이슈가 없었거든요.

별다른 문제가 없었는데 안되는 것이라면 다음의 문제를 한 번 생각해볼 수 있겠네요.
1) 데이터가 적어서 제대로 학습이 안된 경우
- 학습이 제대로 안된다 한들 one token prediction이 일어나지는 않을 것 같음.
2) 인퍼런스가 제대로 안되는 경우. 
- 문장->토큰A를 예측하면 그 다음 스텝으로는 문장+토큰A->토큰B 이렇게 예측 토큰A을 이어붙여서 다음 토큰B을 예측해야함
-  그러나 토큰을 이어붙이는 과정이 안이뤄지고 문장->토큰A만이 계속 반복이 되는 경우

제 생각에는 one token prediction이니 왠지 2)문제일 것 같아요. 음 한 번 인퍼런스 코드를 직접 짜보시겠어요? 
[코드](https://github.com/rungjoo/Stable-Style-Transformer/blob/master/generation_model/yelp/gen_model.py)에서 generated_sentence 함수를 참고하시면 될 것 같아요.

**Comment by janguck** [comment]
답변 감사합니다. 

문제를 해결하였습니다. 
추가적으로 torch==1.2에서는 돌아가는데 torch > 1.2에서는 
"RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 50259]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!"
에러가 나는데 "1.5 이전에 그레디언트에 대한 테스트가 최적화 프로그램에 대해 제대로 작동하지 않아 오류가 표시되지 않았다고 합니다. 그래서 계산 된 기울기는 정확하지 않았다." 라는 [글이 있길래](https://discuss.pytorch.org/t/solved-pytorch1-5-runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation/90256/2) 

[다음 글을](https://discuss.pytorch.org/t/runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation-code-worked-in-pytorch-1-2-but-not-in-1-5-after-updating/87327) 참고하여 

`/generation_model/yelp/model.py`  129 줄의 코드를 143 줄로 옮겨 해결 되었습니다. 
```
gen_trainer.zero_grad()
with torch.autograd.set_detect_anomaly(True):
    gen_cls_loss.backward(retain_graph=True) # retain_graph=True
grad_norm = torch.nn.utils.clip_grad_norm_(genmodel.aed_params, max_grad_norm)
gen_trainer.step()
aed_trainer.step()
```

답변 감사했습니다.

**Comment by rungjoo** [comment]
해결되셨다니 다행입니다. 다른 오류까지 잡아주셔서 감사합니다. 좋은 리뷰 감사합니다~~
