### ISSUE TITLE
ModuleNotFoundError: No module named 'dis_model'

### ISSUE THREAD

**Issue by mriganktiwari** [rungjoo/Stable-Style-Transformer#6]
Issue with ```dis_model``` in ```generation_model/yelp/train.py```
While training the generator as per [this](https://github.com/rungjoo/Stable-Style-Transformer#step-2-train-generator):

- What does ```dis_model``` or the ```sys.path.insert``` refer to in line# 20:21 respectively?
- Should it be ```gen_model``` instead?

Kindly help, thanks.

**Comment by rungjoo** [comment]
Sorry the code is not clear.
`dis_model` you mentioned is the file in the link below.
https://github.com/rungjoo/Stable-Style-Transformer/tree/master/generation_model/yelp/classifier
