### ISSUE TITLE
Please provide Outputs

### ISSUE THREAD

**Issue by sharan21** [rungjoo/Stable-Style-Transformer#7]
Hello,

Please consider releasing you outputs for yelp and amazon so that people can easily use it to compare as a baseline.

**Comment by rungjoo** [comment]
Our code results are in the following folder:

*Model description*
(example)
sentiment.test.{class}.SST_50_06 menas "alpha: 0.6, beta: 0.5".
- class: 0 or 1

*For Amazon*
- paper version: https://github.com/rungjoo/Stable-Style-Transformer/tree/master/evaluation/amazon/my_model_paper
- other: https://github.com/rungjoo/Stable-Style-Transformer/tree/master/evaluation/amazon/my_model_v2

*For Yelp*
- paper version: https://github.com/rungjoo/Stable-Style-Transformer/tree/master/evaluation/yelp/my_model/SST
- others: https://github.com/rungjoo/Stable-Style-Transformer/tree/master/evaluation/yelp/my_model/{others}
