### ISSUE TITLE
해당 모델을 한국어 데이터로 학습하고 싶은데 궁금증이 생겨 문의드립니다.

### ISSUE THREAD

**Issue by greenare** [rungjoo/Stable-Style-Transformer#8]
안녕하세요 텍스트 스타일 변화를 연령대 별로 해보고 싶어서 aihub에서 연령대 별 명령어음성 데이터(https://aihub.or.kr/aidata/33337) 를 다운받아 학습을 진행해보고 있는데요, 말투가 큰 차이가 나지 않아서 reconstruction_loss가 줄어들지 않는 것인지, 아니면 해당 모델에서 학습을 진행할 때 주의할 점이 있을까요?

koGPT2 토크나이저를 사용해주고, vocab file을 huggingface에서 확인하여 pad_idx, start_idx, end_idx를 수정하였습니다.

전체 학습과정의 20% 정도를 진행한다음 텐서보드로 loss를 확인해보니 11 근처에서 진동하는 형태를 띄고 있습니다.

**Comment by rungjoo** [comment]
안녕하세요. 재밌어보이는 시도를 하고 계시네요!

음.. 말씀하신대로 한국어 모델들로 바꾸면 되지 않을까 싶은데요..

먼저 step1에서 classifier을 학습하셨다면, classifier가 제대로 작동하는지 확인해보면 좋을거 같아요.
물론 여기서 classifier을 학습하기 위해, 한국어 토크나이저로 바꿔야겠죠?
(https://github.com/rungjoo/Stable-Style-Transformer/blob/master/generation_model/yelp/classifier/train.py#L10)
아니면, 그냥 한국어 bert나, 다른 classifier을 만들어서 사용해도 문제없구요.

classifier가 제대로 작동한다고 가정하면, 생성모델 학습에서는 말씀하신대로 토크나이저랑 그에맞는 파라미터들 조금 수정하면 될 거 같은데..ㅠ

코드를 크게 건드리는거없다면 딱히 주의할점은 안떠오르네요.. 
학습이 되는지는, 학습 중간에 loss을 보는 것보다는 reconstruction을 inference해봐서 제대로 되는지 확인해보면 될 거 같아요. 추가적으로 style 인자를 바꿔서 스타일이 바뀌는지도 보면 좋을거 같구요.

참고로 오래되서 잘 기억은 안나는데 loss만으로는 제대로 학습되는지 판별하기가 어려웠어요. 즉 loss가 이쁘게 안떨어져도 실제론 그럴싸하게 학습될 수도 있다는거죠. 어차피 reconstruction이 목표가 아니기 때문인거죠.

글만 봐서는 정확히 어떤게 문제인지 모르겠네요ㅠㅠ;; 

아 또 여담으로 저도 NSMC 데이터로 한국어 스타일변환을 간단히 해본적이 있는데 잘되지는 않았어요. 물론 이모델은 아니고 다른 모델로 시도했었고 NSMC 자체가 깔끔한 데이터는 아니긴하죠. 저는 아무튼 약간 문법이나 유창함? 이런게 너무 부족한 느낌이었거든요.

**Comment by greenare** [comment]
안녕하세요 답변 남겨주셔서 감사합니다.
yelp 폴더에 있는 inference.ipynb 파일을 통해 reconstruction 및 style transfer 결과도 같이 공유하겠습니다.

저는 어린아이의 발화를 0으로 두고 노인의 발화를 1로 두고 진행하였고, inference code 진행결과 다음과 같았습니다.

Original Attribute:  0
Original Sentence:  사이렌이 오 분 동안 안 꺼지면 아빠한테 전화 걸어 줘.
Delete Sentence: 사이렌이 오 분 동안 꺼 아빠, 47.05882352941176%
Reconstruction(decoder) Sentence:  에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지
Style transfer(generator) Sentence [0.0, 1.0] :  에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지

Original Attribute:  1
Original Sentence:  어느 호텔이 공항 주변에서 숙박료가 제일 저렴한가?
Delete Sentence: 어느 호텔이 공항 주변에서 숙박, 45.45454545454546%
Reconstruction(decoder) Sentence:  에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지
Style transfer(generator) Sentence [1.0, 0.0] :  에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지 에너지

Classifier는 잘 되는 것 같아요.. 다만 Reconstruction의 경우 계속 한 단어로 예측이 되네요.
Closed issue를 보니 저와 비슷한 경우를 겪은 분이 계셨는데, 코드를 조금 수정하셨다는데 그걸로 해결이 가능한걸까요? 해당 이슈에 댓글을 적어주신 것처럼 다음 단어 예측 방식을 바꿔야할까요ㅜㅜ

한국어 텍스트 스타일 변화가 어렵네요ㅠㅠ

**Comment by rungjoo** [comment]
공유해주신 결과를 보니, 아예 학습이 안되고 있는거 같아 보이네요.

https://github.com/rungjoo/Stable-Style-Transformer/issues/2#issuecomment-753815340
이 이슈를 말씀하신거 맞죠? 여기서도 같은 토큰들이 반복되는 문제가 있었는데 이거대로 해보시면 어떨가 싶네요.

이  실험을 할때의 라이브러리 버전들이 오래됐기도했고.. 옛날에 주먹구구 식으로 돌아가게끔 했던거 같아서 지금 돌릴때 뭔가 코드들이 깔끔하지않고 문제가 있어보이긴 하네요.
