### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 50259]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by ayssedgrmnci** [rungjoo/Stable-Style-Transformer#9]
Hello, first of all, thank you very much for sharing the project with us.
I faced the following problem in the train generator step.

Traceback (most recent call last):
   File "train.py", line 162, in <module>
     main()
   File "train.py", line 141, in main
     gen_cls_loss.backward() # retain_graph=True
   File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 487, in backward
     torch.autograd.backward(
   File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 197, in backward
     Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 50259]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

There are people who solved it using clone() but I couldn't. Please your help. Thanks have a good day.

**Comment by rungjoo** [comment]
It seems to be similar to the this [issue](https://github.com/rungjoo/Stable-Style-Transformer/issues/2#issuecomment-753815340), have you followed it?
In the experimental environment torch>1.2, it is recommended to move the 129 line to the 143 line.

**Comment by ayssedgrmnci** [comment]
sorry i didn't see the other issue, thanks a lot for your help. The other thing I'm wondering is with which extension the trained model is registered and how can I run this model in the current time?

**Comment by rungjoo** [comment]
[Link]([https://github.com/rungjoo/Stable-Style-Transformer/blob/master/generation_model/inference.ipynb](https://github.com/rungjoo/Stable-Style-Transformer/blob/master/evaluation/amazon/my_model_paper/generalization_eval_new.ipynb)) is the model inference code and [link](https://github.com/rungjoo/Stable-Style-Transformer/blob/master/evaluation/amazon/my_model_paper/generalization_eval_new.ipynb) is the code that evaluates the model result.
Please refer to the above two codes for help.

You can refer to the paper for the model structure.
The result of the trained model is shown at [link](https://github.com/rungjoo/Stable-Style-Transformer/tree/master/evaluation).
